#!/usr/bin/bash


androidsdk="$HOME/android/sdk"
downloadurl="https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip"
downloadfilename="file.zip"

clear
sleep 0.5 && echo ""
mkdir -pv $androidsdk
sleep 0.5 && echo ""
cd $androidsdk
sleep 0.5 && echo ""
curl -# -o $downloadfilename $downloadurl
sleep 0.5 && echo ""
unzip $downloadfilename -d cmdline-tools
sleep 0.5 && echo ""
mv cmdline-tools/cmdline-tools cmdline-tools/tools
sleep 0.5 && echo ""
cd $HOME/android
sleep 0.5 && echo ""
curl -# -O https://gist.githubusercontent.com/nonaybay/df1aeb3753610d85020cbf454cfb46e7/raw/4feea357deff45d66dddffb9474a1c7c0cde150f/init
sleep 0.5 && echo ""
echo "source ${HOME}/android/init" >> $HOME/.bashrc
